### PR TITLE
Added anti-aliasing to VERA PSG waveforms

### PR DESCRIPTION
**Pull request by TaleTN**
This adds anti-aliasing using polyBLEPs to the pulse/sawtooth waveforms. It also includes anti-aliasing for the triangle waveform, but this is disabled, because it's good enough as it is (IMHO, YMMV).

This will obviously be slower than without anti-aliasing (so maybe it should be optional?), but performance should still be pretty good.

It should probably be tested some more, because although it seems to work fine in isolation, I haven't yet tested it in the actually emulator itself...

BTW, I assume the actual VERA PSG hardware doesn't suffer from aliasing, right?

### CODE REVIEW

**Comment by mist64** [comment]
Happy to merge this. What's with the commented-out code though?

Sorry for the late comment.

**Comment by TaleTN** [comment]
> What's with the commented-out code though?

I also implemented anti-aliasing for the triangle waveform. However, aliasing in the triangle is already barely audible, so I think it's not worth the trouble. But if anyone wants to try for themselves, then they would need to uncomment the code.

Anyway, you could leave that code out, or else maybe I could add some macro that enables/disables the code.

**Comment by mist64** [comment]
Can you please format it so that:
* the functions that do the work are actually in the code, not commented out (so the compiler sees them and will spot any build problems in the future)
* the call to the function is guarded by `#if 0 // enable this for blabla`

**Comment by TaleTN** [comment]
Yeah sure, that is: I've moved most of the code to static functions that are always compiled, but I've also added some macros to enable anti-aliasing. The latter is necessary (IMHO), because else the channel struct would include unsed variables, and the set_freq() function would do unnecessary calculations.

**Comment by TaleTN** [comment]
FYI: I've just fixed (amended) the 2nd commit, because I forgot to update the argument order in the poly_blamp() call, oops!

**Comment by TaleTN** [comment]
I've just found another issue with the triangle anti-aliasing, so I will amend the 2nd commit again soon.

**Comment by akumanatt** [comment]
The actual VERA doesn't do any kind of anti-aliasing (see https://github.com/fvdhoef/vera-module/blob/rev4/fpga/source/audio/psg.v#L159) and generates PSG samples at only 48 KHz.

Also this commit breaks building.

**Comment by TaleTN** [comment]
> The actual VERA doesn't do any kind of anti-aliasing (see https://github.com/fvdhoef/vera-module/blob/rev4/fpga/source/audio/psg.v#L159) and generates PSG samples at only 48 KHz.

If that's the case, then I guess it's probably better to not use any anti-aliasing in the emulator as well.

But if the actual VERA is generating digital samples at only 48 kHz, then having no anti-aliasing at all will probably sound pretty bad (i.e. worse than an oldskool PSG), especially at higher frequencies.

**Comment by mist64** [comment]
@fvdhoef?

**Comment by fvdhoef** [comment]
It is as akumanatt says. There is no anti-aliasing. There is some audible aliasing, especially with the triangle waveform. But it doesn't sound too bad in my opinion. There aren't enough resources to implement something more sophisticated.

**Comment by mist64** [comment]
Should we make the feature opt-in then, with a command line argument?

**Comment by fvdhoef** [comment]
Well the emulator would then be better than the real hardware. Not that useful in my opinion.

**Comment by TaleTN** [comment]
> There is some audible aliasing, especially with the triangle waveform. But it doesn't sound too bad in my opinion. There aren't enough resources to implement something more sophisticated.

Do note that, although I haven't heard the actual VERA, I'm not sure if what you are hearing in the triangle actually is aliasing. Because of the limited bit depth the triangle would be rather noisy anyway, which would almost certainly mask any aliasing. Aliasing would likely be most noticable when doing a frequency sweep using a square wave. Also note that the aliasing was bad enough for me to notice it while watching a YouTube video of the emulator, but YMMV.

> Well the emulator would then be better than the real hardware. Not that useful in my opinion.

I would agree.

**Comment by akumanatt** [comment]
I think what is really needed here is a proper resampling from both YM's output buffer and VERA's output buffer to target sample rate. This would reduce additional aliasing.

**Pull request merged**
