### PR TITLE
Initial phase in formatting build script for readability

### PR DESCRIPTION
**Pull request by jeriesar94**
Initial attempt in trying to reformat and rewrite small parts of the script for better readability.

### CODE REVIEW

**Comment by mist64** [comment]
@ paulscottrobson will have to decide on this, and he's on vacation for another ~10 days. :/

**Comment by paulscottrobson** [comment]
Fine with me if it works. The odd formatting was so I could visually compare the tables with the original hand created ones. That’s no longer necessary if it just improving layout and formatting

**Comment by jeriesar94** [comment]
I will keep everything as is, It's just improving the readability of the script and making it easier to modify... even though that default names might not change.. such as "tables.h"

**Comment by paulscottrobson** [comment]
Fine by me as long as mist64 okays it

**Comment by mist64** [comment]
Whoops, I tried this *after* merging, and I get this:

Traceback (most recent call last):
  File "buildtables.py", line 161, in <module>
    generateTable(output_h_file, ADDR_MODE_HEADER, MODE_KEY_STR)
  File "buildtables.py", line 108, in generateTable
    formattedOpcodeLine = "{0:>9}".format(opcodesList[opcodeItem][element])[-spacing:]
NameError: name 'opcodeItem' is not defined

**Comment by jeriesar94** [comment]
> Whoops, I tried this _after_ merging, and I get this:
> 
> Traceback (most recent call last):
> File "buildtables.py", line 161, in
> generateTable(output_h_file, ADDR_MODE_HEADER, MODE_KEY_STR)
> File "buildtables.py", line 108, in generateTable
> formattedOpcodeLine = "{0:>9}".format(opcodesList[opcodeItem][element])[-spacing:]
> NameError: name 'opcodeItem' is not defined

Opps my bad I had another commit that was not submitted :(

**Pull request merged**
