### PR TITLE
Fix SYS bug on autorun

### PR DESCRIPTION
**Pull request by paulscottrobson**
Fixed the SYS call which used %x ; this generated L/C call addresses ; simplified to %d

### CODE REVIEW

**Comment by paulscottrobson** [comment]
Sorry for the stupid name. This is a fix to the SYS problem ; %x was generating l/c hexadecimal values, so code running from RAM banks didn't work. Simplest solution, always use decimal.

**Comment by mobluse** [comment]
This is issue https://github.com/commanderx16/x16-emulator/issues/139. Another possibility was to change x to X.

**Comment by marksassistants0** [comment]
Hi does anyone know what this is and why it’s stored in my files 


Sent from Yahoo Mail for iPhone


On Friday, November 1, 2019, 6:57 PM, Mikael O. Bonnier <notifications@github.com> wrote:


This is issue #139. Another possibility was to change x to X.

**Comment by marksassistants0** [comment]
{"timestamp":"2019-10-13 00:01:39.77 -0400","bug_type":"225","os_version":"iPhone OS 13.1.2 (17A860)","incident_id":"3C352579-4CB2-4C62-AB10-81496D437858"}[{"osVersion":"13.1.2","rangeEndTime":1570939299,"eventVersion":1,"eventType":"launches","foregroundDuration":3692,"topic":"xp_amp_app_usage_dnu","bundleId":"com.google.ios.youtube","shortAppVersion":"14.40.2","itemId":"544007664","count":4,"appVersion":"1.0","externalVersionId":"833030551","baseVersion":1,"bundleVersion":"14.40.2","eventTime":1570939299552,"clientEventId":"6BF710E0-6338-4CFA-8B65-2BF340F77DE2","usageClientId":"C006632E-6817-4552-8F78-3F0F98D1281C","timezoneOffset":240,"app":"com.apple.appstored","rangeStartTime":1570896023},{"osVersion":"13.1.2","rangeEndTime":1570939299,"eventVersion":1,"eventType":"launches","foregroundDuration":795,"topic":"xp_amp_app_usage_dnu","bundleId":"com.facebook.Messenger","shortAppVersion":"235.0","itemId":"454638411","count":22,"appVersion":"1.0","externalVersionId":"832925363","baseVersion":1,"bundleVersion":"175338100","eventTime":1570939299553,"clientEventId":"8DF664E1-7CA7-4D79-8745-DD5EAAFCE8DB","usageClientId":"C006632E-6817-4552-8F78-3F0F98D1281C","timezoneOffset":240,"app":"com.apple.appstored","rangeStartTime":1570896023},{"osVersion":"13.1.2","rangeEndTime":1570939299,"eventVersion":1,"eventType":"launches","foregroundDuration":1055,"topic":"xp_amp_app_usage_dnu","bundleId":"com.facebook.Facebook","shortAppVersion":"241.0","itemId":"284882215","count":9,"appVersion":"1.0","externalVersionId":"832940524","baseVersion":1,"bundleVersion":"175508976","eventTime":1570939299554,"Sent from Yahoo Mail for iPhone


On Friday, November 1, 2019, 10:34 PM, Rose DiFrancesco <r_petal1@yahoo.com> wrote:

Hi does anyone know what this is and why it’s stored in my files 


Sent from Yahoo Mail for iPhone


On Friday, November 1, 2019, 6:57 PM, Mikael O. Bonnier <notifications@github.com> wrote:


This is issue #139. Another possibility was to change x to X.

**Comment by greg-king5** [comment]
> Sorry for the stupid name.

You can change that name.  Look for an "Edit" button off to the right of the PR's title.  Click it, edit the text, then click the "Save" button near the right side of the edit box.

**Comment by paulscottrobson** [comment]
> This is issue #139. Another possibility was to change x to X.

Yes it is. I'm running code in banked RAM, which doesn't work without this fix.

**Comment by mist64** [comment]
I would very much prefer uppercase hex (%X) instead of decimal. :)

**Comment by paulscottrobson** [comment]
It doesn't really matter either way :)

**Comment by mist64** [comment]
Fixed in 881c3ae.

**Pull request closed without merging**
