### PR TITLE
Basic examples

### PR DESCRIPTION
**Pull request by daitangio**
A set of basic examples found on the Facebook page. Added also a classic "maze" example, taking advantage of the 80 columns display

### CODE REVIEW

**Comment by indigodarkwolf** [comment]
Should these examples go to https://github.com/commanderx16/x16-demo, instead?

**Comment by mobluse** [comment]
I think there should be a separate repository for example X16 BASIC programs in text form, i.e. programs that can be loaded with ./x16emu -bas path/to/file.bas

**Comment by indigodarkwolf** [comment]
Or maybe move the assembly examples into a subdirectory of the x16-demo repo, and the BASIC programs live in a different subdirectory?

**Comment by daitangio** [comment]
Ok, I got it :)
I will make a pull request soon, okey?

Please excuse typs as Sent from my iPhone

**Comment by indigodarkwolf** [comment]
Looks like these got pulled into https://github.com/commanderx16/x16-demo, can we close this?

**Pull request closed without merging**
