### PR TITLE
issue #51: Draw optimizations

### PR DESCRIPTION
**Pull request by indigodarkwolf**
Some simple optimizations to get_pixel and get_sprite which reduce overhead from needlessly recalculating values that only change with layer and sprite attribute changes. Current layer and sprite properties are calculated into structs that can be referenced instead of performing the math for each pixel.

In my profiling, the largest single hotspot remaining in get_pixel() and get_sprite() seems to be the calls to video_space_read(), and my best guess is that branch instructions are causing needless stalling when it would be faster to perform a bitwise-and in the special cases of get_pixel() and get_sprite(). That last tweak is pending a question in issue #51.

### CODE REVIEW

**Comment by hasenbanck** [comment]
The commit history of this PR looks like you used PRs on your own repository to sync the current branch into your feature branch. I think it would be best if you squash your commits and rebase them against the current master and do a force push. That way we keep the commit history clean.

**Comment by indigodarkwolf** [comment]
Assume I don't know what I'm doing in git. Do you mean I should discard my fork, re-fork, and essentially paste the changed file into the clean fork?

**Comment by mist64** [comment]
If it’s just a single file, pasting the file into a clean fork would be easiest. :-) (git is hard!)

**Comment by indigodarkwolf** [comment]
Git _is_ hard. >.> And my dayjob uses Perforce.

**Pull request closed without merging**
