### PR TITLE
Enforce editorconfig style by travis CI + fix style violations

### PR DESCRIPTION
**Pull request by madebr**
- Let Travis-CI enforce editorconfig rules (and fail CI when a violation is found)
- Fix all current style violations:
  * I've moved `gif.h` and `ym2151.[ch]` to an external folder as these are files not *owned* by ths project (and keep the diff to the original small)
  * Ignore styles for the `cpu` and `extern` directory, as (most of) these files are included from external projects

Status before this pull request: https://travis-ci.com/madebr/x16-emulator/jobs/239039488
Status after this pull request: https://travis-ci.com/madebr/x16-emulator/jobs/239067490 (no violations)

### CODE REVIEW

**Comment by madebr** [comment]
Rebased on current master.

**Comment by mist64** [comment]
This looks like a good idea, but I have no experience with anything like this, so here's my question: Will this complain about the style of pull requests, so people offering a pull request will know what to change? Or will it only tell **me** what is wrong after **I** merge it?

**Comment by madebr** [comment]
@mist64 Yes, the check will be performed every time travis-ci performs a build, which is on every action on the git tree of this repository: a push to a branch, tagging of a commit, on every pull request, ...
The author of the pull request can check whether all tests are in the green and fix his pull request.
You as the maintainer of this project will always have the final decision on merge/no-merge.

**Comment by rsbohn12** [comment]
Is it possible to have just one .editorconfig file?

**Comment by madebr** [comment]
I created multiple because the files in `extern` and `cpu` have spaces instead of tabs.
I think another file tree can merge this.
e.g. put all extern sources in `extern/...` and all project specific sources in `src/...`.
The `.editorconfig` can then specify tabs for all `src/*.c` and don't specify anything for sources in `extern`.
`.editorconfig` are meant to be used by editors, not for checking rules. `clang-format` might be something useful to look into.

**Pull request merged**
