### PR TITLE
Add CMake support equivalent to Makefile

### PR DESCRIPTION
**Pull request by madebr**
This pr add support for the CMake build system. This allows building x16-emulator on Visual Studio.
It is based on #64 (rebased, squashed and with small modifications).
In addition, it adds:
- documentation generation using CMake,
- releases creation using CMake,
- emscripten support using CMake,
- cmake tests on CI services: [travis-ci](https://travis-ci.com/madebr/x16-emulator) and [Appveyor](https://ci.appveyor.com/project/madebr/x16-emulator/builds/28400348)
  * appveyor ci provides artifacts: [visual studio 32-bit](https://ci.appveyor.com/project/madebr/x16-emulator/builds/28400348/job/byo645rkt3332j88/artifacts), [visual studio 64-bit](https://ci.appveyor.com/project/madebr/x16-emulator/builds/28400348/job/9myqpjor0xyjqv35/artifacts), [emscripten](https://ci.appveyor.com/project/madebr/x16-emulator/builds/28400348/job/wnjmndq519kkm7nq/artifacts) or [mingw 64-bit](https://ci.appveyor.com/project/madebr/x16-emulator/builds/28400348/job/5fhv13urcld1ojoj/artifacts)
- support for [conan](https://conan.io/): conan is a package manager aimed to developers that provides development packages. It is greatly useful for providing mingw on windows, emscripten on windows and linux and providing sdl2 on all platforms. I'm using it on appveyor and in the emscripten test on travis-ci.
  * I made sure that the cmake script contains no conan references.

@vii1: Please test
@sebastianvog @Frank-Buss : Please test emscripten/webassembly support + give blessing :laughing:

### CODE REVIEW

**Comment by madebr** [comment]
I rebased this pr on current master (and use release 34 on ci)

**Comment by sebastianvog** [comment]
@madebr anytthing particular you want me to check for emscripten? i am unfamiliar with cmake, but i can give it a try.

**Comment by madebr** [comment]
Hey @sebastianvog,
Just checking whether your *workflow* still works and if there is something wrong/missing.
The only difference should be the cmake configure step and an out-of-tree builds.

**Comment by nigels-com** [comment]
cmake makes me sad.  But I don't have a better suggestion, unfortunately.

**Comment by madebr** [comment]
I'll close this one as cmake/Visual Studio support is unwanted atm.

**Pull request closed without merging**
