### PR TITLE
65C02 Opcode upgrade

### PR DESCRIPTION
**Pull request by paulscottrobson**
65C02 fixes:

- split fake6502.c into subcomponents
- autogenerates tables, disassembly (hence disasm.c changed)
- seperate file with 65C02 new stuff
- small changes to 6502 for 65C02 compatibility (see README in cpu)

### CODE REVIEW

**Comment by sebastianvog** [comment]
chargen.bin and rom.bin should not be committed, or ? Perhaps those two files should get added to .gitignore so it is not accidently part of a commit.

**Comment by mist64** [comment]
Also, cpu/tables.h.org doesn't seem it should be part of this.

**Comment by mist64** [comment]
I fixed the issues and merged it as ac46b2a.

**Comment by mist64** [comment]
P.S.: Thanks Paul! :)

**Pull request closed without merging**
