### PR TITLE
Replacing mults and divs with power-of-two adds.

### PR DESCRIPTION
**Pull request by indigodarkwolf**
This should be a properly reconciled set of changes with my previous PR, tested with ChaseVault, my X16 demos, and the sample sprite collide samples I wrote in https://github.com/indigodarkwolf/x16-samples/tree/master/sprites-collision.

### CODE REVIEW

**Comment by indigodarkwolf** [comment]
I don't know why it insisted that I re-resolve things by hand, but whatever.

**Comment by mist64** [comment]
Awesome. I'm measuring a speedup of about 20% on macOS.

**Comment by sasq64** [comment]
Great indeed, a lot of changes and I very much doubt it was replacing muls with shifts that caused the speed up.

**Comment by indigodarkwolf** [comment]
Well, not entirely, anyways, and certainly not on Intel platforms. This
also removed a lot of branching, which was probably the dominant
contributor.

**Pull request merged**
