### PR TITLE
Zero Page Register display in debugger

### PR DESCRIPTION
**Pull request by mjallison42**
This PR adds zero page register display to the emulator debugger screen. It also adds change detection for ease of use during debugging.

### CODE REVIEW

**Comment by mist64** [comment]
Cool, but can you please change the coding style to match the existing one in this file?

**Comment by mjallison42** [comment]
> Cool, but can you please change the coding style to match the existing one in this file?

Pleased to do so. Can you be explicit about which elements don't match? (coding style is a broad topic)

**Comment by mjallison42** [comment]
> Cool, but can you please change the coding style to match the existing one in this file?

Are you suggesting refactoring the code into it's own routine?

**Comment by greg-king5** [comment]
> > Cool, but can you please change the coding style to match the existing one in this file?
> 
> Pleased to do so. Can you be explicit about which elements don't match (coding style is a broad topic)?

Look at the spaces that you put next to the characters '*', '(', and ')'.  Also, you didn't put a space after `if`.

**Comment by mjallison42** [comment]
Refactored and incorporated formatting changes (thanks greg-king5).

**Pull request merged**
