### PR TITLE
Gif recording capability

### PR DESCRIPTION
**Pull request by neilogd**
Make recording to a GIF trivial by commandlike "-gif test.gif"

### CODE REVIEW

**Comment by neilogd** [comment]
Might do a little more refinement of this, does work, but the animation delay seems to be a bit much.

**Comment by mist64** [comment]
Awesome. Can you try to make the coding style (of the changes; I'm not talking about gif.h) a little more consistent with the existing code though, please? It's basically BSD style.

* asterisk with the variable, not the type.
* open brace on the same line
* space after keywords like `if`
* always braces after `if`

Thanks!

**Comment by neilogd** [comment]
Should be sorted now. Frame rate of the recorded gif still doesn't seem right. In the past when embedding this in projects I've added a frame skip function to avoid exporting as many frames, and achieve better playback speed. Some image viewers seem to respect the 10ms frame delay, where as browsers seem to not, frustratingly.

**Comment by neilogd** [comment]
Aaand there we are, a nice to look at frame rate: https://twitter.com/neilogd/status/1173186178062749696

**Comment by Kroc** [comment]
Suggestion: APNG is an easy format to write and would be smaller in practice than GIF.

**Comment by mist64** [comment]
Great work, great feature. Thanks.

**Pull request merged**
